---
title: "Lab 06 - Functions and iterations"
author: "Charlie Franklin-White"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}
# Do some preliminary investigations & cleaning

#Frequency Table of cut type

diamonds %>%
  group_by(cut) %>%
  summarise(
    count = n()
  )
  

#Frequency table of clarity

diamonds %>%
  group_by(clarity) %>%
  summarise(
    count = n()
  )

#Filtering and removing problematic measurements

diamonds <- diamonds %>%
  filter(length_mm != 0 | width_mm != 0 | depth_mm != 0)



```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?

diamonds %>%
  summarise(
    mean_table = mean(table_mm)
  )

# table_mm arithmetic mean within each clarity category

diamonds %>% 
  group_by(clarity) %>%
  summarise(
    mean_table = mean(table_mm)
  )





```

It appears that, as the diamond becomes clearer I1 to IF, the average table length decreases. 

```{r}
# calculate the arithmetic mean across all numeric variables

diamonds %>%
  summarise(
    across(where(is.double), mean, .names = "avg_{col}")
  )

```

## Exercise 3

```{r}
# # Write gmean() command

gmean <- function(x){
  n = length(x)
  
  sum = 0
  
  for (i in 1:n){
    sum = sum + log(x[i])
  }
  
  geo_mean <- exp((1/n) * sum)
  
  return(geo_mean)
}

```

## Exercise 4

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples

for (i in 1:length(test_data)){
  print(gmean(test_data[[i]]))
}


```


## Exercise 5

```{r}
# Copy gmean() from Ex 3 and edit it to check the input

gmean <- function(x){
  
  if( any(x <= 0) ){
    warning("Enter stricly positive data only.")
    return(NaN)
  }
  
  if( !any(is.numeric(x))){
    warning("Enter numeric data only")
    return(NaN)
  }
  
  n = length(x)
  
  sum = 0
  
  for (i in 1:n){
    sum = sum + log(x[i])
  }
  
  geo_mean <- exp((1/n) * sum)
  
  return(geo_mean)
}


# Copy your code from Ex 4 to test your new command

for (i in 1:length(test_data)){
  print(gmean(test_data[[i]]))
}



```

## Exercise 6

```{r}
# replicate the for loop from Ex 4 using the map (or a similar) function

map_dbl(test_data, gmean)

```


## Exercise 7

```{r}
# Overall table_mm arithmetic mean, median, and geometric mean?






# Arithmetic mean, median, and geometric mean of table_mm within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```

## Exercise 10 (optional)

_Do derivation on paper, unless you know how to write LaTeX code_
